module Money
  class Money
    include Comparable

    attr_reader amount: Integer

    def self.dollar: (Integer) -> Money
    def self.franc: (Integer) -> Money

    def <=>: (Money) -> (Integer | nil)
  end

  class Dollar < Money
    def initialize: (Integer) -> void
    def times: (Integer) -> Money
  end

  class Franc < Money
    def initialize: (Integer) -> void
    def times: (Integer) -> Money
  end
end
